### ISSUE TITLE
Detaily potřeby srid=0

### ISSUE THREAD

**Issue by raugustyn** [raugustyn/TB04CUZK001_R2#18]
Po detailnějším rozmyšlení požadavku na srid, které by bylo nulové mám pocit, že kromě nesystémovosti je to zbytečné.

Naprosto chápu, že v rámci obchodního modelu by v budoucnosti chtěly T-Mapy řešení rozvíjet a nasadit třeba ve Švédsku. To má logiku. Ale i tam bych očekával správné nastavení souřadného systému. Nastavit systém lze přece velice jednoduše ve všech SQL dotazech při jejich vytvoření.

Jako akceptovatelné řešení pro TB04CUZK001 bych přijal napevno nastavených 5514, ale raději formou konstanty v konfiguraci systému. Z toho se vygenerují všechny scripty, když ne jinak tak pomocí search and replace.

Je v tom opravdu nějaký problém?

Viz také:
[MindMapa z jednání v Hradci](https://drive.mindmup.com/map/0BxN4f7YDRtuqV3pwNjJfYUVHNE0)
[Ověřit, jak se GeoTools API chová při SRID=0 #13](https://github.com/raugustyn/TB04CUZK001_R2/issues/13)

**Comment by LabyrinthTechnology** [comment]
Já se budu #13 věnovat tento týden (ve smyslu praktického ověření). Z toho, co jsem si zatím vyhledal v různých diskusích, mi to vychází tak, že fungovat to bude, ale srid=0 je chápáno spíše jako příznak "něco je špatně" (protože určení referenčního systému je chápáno jako nedílná součást definice feature) než jako "pracuji v neurčené XY rovině".

Chápu argumenty zmíněné TB04CUZK001_Jelen v [této odpovědi](https://github.com/raugustyn/TB04CUZK001_Jelen/issues/16).

Osobně mi v této chvíli asi více vadí ta nesystémovost "zahodit informaci, která je nativní pro každý feature".

**Comment by to-kr** [comment]
Rozumím tomu názoru. V datech geometrií můžeme ponechat SRID, který bude nastaven při importu dat. Jen zůstaňme bez nastavení constraint na SRID v definici tabulky. Bude tak možno použít stejné řešení pro různé souřadnicové systémy.

**Comment by raugustyn** [comment]
Motáme se v kruhu. Nahradit automaticky jedinečný řetězec ", 5514" za "" je otázka vteřin. Opačně to nejde. Nevytvářejme slepé uličky.

**Comment by to-kr** [comment]
Do konfigurace (admin/config.bat) byla doplnena moznost nastaveni SRID. Zaroven byl upraven restore a loader. Budeme tedy podporovan moznost nastaveni SRID i PostgreSQL.

**Comment by raugustyn** [comment]
Super, díky za pochopení.
