### ISSUE TITLE
Převést kód modulu 1 do repository

### ISSUE THREAD

**Issue by LabyrinthTechnology** [raugustyn/TB04CUZK001_R2#3]
Převést stávající do repository

Preferuje se převést kód do repository rychle bez nutného přizpůsobení např. dohodnutému výměnnému datovému modelu a až následně kód, již v tomto repository, dále upravovat a rozvíjet.

Kritérium pro dokončení:
* Kód pracuje (nemusí nezbytně nad standardní výměnnou megatabulkou)
* Aplikace odpovídá dohodnutým požadavkům (vlastní namespace m1)

**Comment by to-kr** [comment]
Provedli jsme refactoring kódu a poslali vše do naší GITHUB repository k možnému nahlédnutí. Je tedy hotovo 
- rozdělení kódu do jednotlivých modulů admin + data + m1-3
- vytvoření základních PG schemat pomocí nástrojů v admin
- vytvoření tabulky data.elements (má lehce dopracovanou strukturu)
- oddělení světa m1 (doplnění prefixu m1_ do PG schemat)
- nahrávací skript pro testovací data (jsou rovněž v repository) do tabulky data.elements﻿

čekáme na cílovou repository v souvislosti #14

**Comment by LabyrinthTechnology** [comment]
Můj dojem z workshopu byl takový, že "ta správná" sdílená repository je právě tato a @raugustyn následně zajistí vytvoření (ve spolupráci s @janlangr) nové "společné organizace" v Github (což je právě #14), pod kterou se tato repository přesune.

Pokud dokumentaci ke Githubu chápu správně, tak přesun repository z uživatelského účetu pod organizaci v podstatě nic nemění (otázkou jsou přiřazení issues a jak jsou nastaveny přístupy), takže nemyslím, že je potřeba čekat ... rozhodně nic takového nezaznělo.

**Comment by raugustyn** [comment]
Jo, přesně. Se omlouvám, ale ještě provádíme formální úpravy mnoha obrázků v Nmet2 podle připomínek oponentů, takže k tomuto se ještě chvíli nedostanu. Přesně tak to je jak píše @LabyrinthTechnology, až bude vytvořena organizace, pouze se změní vlastník tohodle repository na jiného pomocí "Transfer Ownership" v nastavení settings.

**Comment by LabyrinthTechnology** [comment]
> Se omlouvám, ale ještě provádíme formální úpravy mnoha obrázků v Nmet2 podle připomínek oponentů, takže k tomuto se ještě chvíli nedostanu.

Myslím, že není za co se omlouvat, navíc jsi tohle nebezpečí avizoval minulý týden na workshopu.

**Comment by to-kr** [comment]
Kód je převeden do develop verze
