### ISSUE TITLE
Vytvořit nástroj pro sdílené struktury v DB

### ISSUE THREAD

**Issue by LabyrinthTechnology** [raugustyn/TB04CUZK001_R2#4]
Ze stávajícího kódu modulu 1 vyseparovat a dále upravit kód, který v DB vytvoří sdílené části DB, především pak:
* schéma data
* tabulku data.elements
* nezbytné související funkce pro načtení dat

Je v podstatě součástí #3.

**Comment by to-kr** [comment]
hotovo v https://github.com/T-MAPY/GenSMD/

**Comment by LabyrinthTechnology** [comment]
Sorry, ale dokud nástroj nebude ve sdílené repository, tak těžko lze issue uzavřít, protože se vztahuje k této sdílené repository a nikoliv k soukromé (ať již pod Rakovým nebo T-Mapy účtem). Takže znovuotevírám.

**Comment by LabyrinthTechnology** [comment]
Vyzkoušel jsem stav v T-Mapy [GenSMD repository](https://github.com/T-MAPY/GenSMD), větev master. Databázi se podařilo vytvořit (data nahrát ale již ne, viz #5), pár poznámek:

* V Prerequisities chybí informace o nutnosti mít nainstalovaný GDAL (případně informace, jak využít GDAL v QGISu).
* Chybí informace o tom, že databáze gensmd musí existovat a skript ji nevytvoří.
* Informace jak nainstalovat xmltodict je asi chybná, podle mne je správně `Scripts\pip3 install xmltodict`.

**Comment by to-kr** [comment]
Mas pravdu, doplnime to, co pises. 
Jeste k xmltodict. Ja mam v adresari Scripts zcela identicke soubory
- pip
- pip3
- pip3.3
tzn. chybu nevidim

**Comment by to-kr** [comment]
Doplneno do admin Readme.md
