### ISSUE TITLE
Implementovat a ověřit načtení základní testovací sady

### ISSUE THREAD

**Issue by LabyrinthTechnology** [raugustyn/TB04CUZK001_R2#5]
Předpokádám v rámci #3 a po dokončení #4:

* Nahrát do repository základní testovací sadu, kterou T-Mapy v současné době používají
* Ověřit její konverzi do struktury sdílené megatabulky
* Vytvořit odpovídající skript spustitelný (asi) jako bat
* Zdokumentovat proces, aby byl opakovatelý i ostatními týmy

**Comment by to-kr** [comment]
hotovo v https://github.com/T-MAPY/GenSMD/

**Comment by LabyrinthTechnology** [comment]
Spuštění `\TM-GenSMD\data\prototype\load-data.bat` skonční takto:
```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
ERROR:  relation "data.temp_elements" does not exist
ŘÁDKA 1: ...elt_id::varchar, ST_SetSrid(wkb_geometry, 0) FROM data.temp_...
```

**Comment by LabyrinthTechnology** [comment]
Vyřešeno, chybka (mezera) v config.bat v definici OGRBIN, chce to krátký bezmezerový zápis cesty ;-)
Takže data jsou v databázi.

**Comment by to-kr** [comment]
vyborne. jsem rad, ze to zafungovalo
